### ISSUE TITLE
Compilation Error in  model 

### ISSUE THREAD

**Issue by afuyo** [tnightengale/dbt-activity-schema#20]
I try follow the example in the repo and run this model 

```SQL 
{{
    dbt_activity_schema.dataset(
        ref("example__activity_stream"),
        dbt_activity_schema.activity(dbt_activity_schema.all_ever(),"visited page"),
        [
            dbt_activity_schema.activity(
                dbt_activity_schema.first_ever(),
                "signed up",
                ["feature_json", "ts"]
            )
        ]
    )
}}
```
But get this error 
```
Compilation Error in model first_ever (models\activity_stream\first_ever.sql)
  unsupported operand type(s) for +: 'dict_values' and 'list'
```

**Comment by tnightengale** [comment]
@afuyo Confirming: you have uploaded the seed of the example activity stream?

Also, can you provide the project vars you are using, if any?

**Comment by afuyo** [comment]
@tnightengale Yes, I've uploaded the seed and use no vars at all. It's really juste hello-world dbt-activity-schema ;)

**Comment by afuyo** [comment]
Here it the entire error message: 
```
Compilation Error in model dataset__first_ever_1 (models/activity_stream/dataset__first_ever_1.sql)
  unsupported operand type(s) for +: 'dict_values' and 'list'

  > in macro dataset (macros/dataset.sql)
  > called by macro default__dataset (macros/dataset.sql)
  > called by model dataset__first_ever_1 (models/activity_stream/dataset__first_ever_1.sql)

```

**Comment by brown5628** [comment]
I am getting the same error with the same parameters (default settings) on Snowflake using dbt 1.3. Happy to provide additional logs/info if it would be helpful.

**Comment by afuyo** [comment]
I was missing these vars in dbt_project.yml in order to make it work. I've added them and I am able to run the examples in the repo. 

````
vars:
  dbt_activity_schema:
    included_columns:
      - activity_id
      - entity_uuid
      - ts
      - revenue_impact
    column_mappings:
      customer: entity_uuid
      anonymous_customer_id: anonymous_entity_uuid

```
