### ISSUE TITLE
TRY_CAST SQL compilation error

### ISSUE THREAD

**Issue by brown5628** [tnightengale/dbt-activity-schema#26]
Hello!

Appreciate the awesome work on this package and am excited to get into using it. 

I'm getting a SQL compilation error when attempting to make use of the package on Snowflake, dbt version is 1.3, dbt-activity-schema version is .32. 

My stream is generated using the narrator activity schema dbt package, and the macro I'm using is:
```sql
        {{
            dbt_activity_schema.dataset(
                ref("account_stream"),
                dbt_activity_schema.activity(
                    dbt_activity_schema.all_ever(), "originates_loan"
                ),
                [
                    dbt_activity_schema.activity(
                        dbt_activity_schema.last_before(), "updates_autopay"
                    )
                ],
            )
        }}
```

Variables from the `project.yml` are:
```yml
  dbt_activity_schema:
      included_columns:
        - activity_id
        - customer
        - ts
        - activity
        - anonymous_customer_id
        - feature_json 
#        - feature_json_str
        - link
        - revenue_impact
        - activity_occurrence
        - activity_repeated_at
```

Error is:

```
Function TRY_CAST cannot be used with arguments of types TIMESTAMP_TZ(9) and VARCHAR(16777216)
```
 
Am I missing something that could get this working as expected? From my own troubleshooting, I see that:

- If I revert to .31 and remove the `feature_json` column from the variable list, I get code that executes.
- Based on the [relevant Snowflake docs](https://docs.snowflake.com/en/sql-reference/functions/try_cast), `try_cast` needs a string as an input, so I would expect that this also will fail for numbers and the `feature_json` object on Snowflake. So `select try_cast(1 as text)` fails but `select try_cast('1' as text)` works.

If I am not missing something and this is a DB specific issue, I'd be interested in understanding how I can help ensure the package is Snowflake compatible.
